package com.maanvith.app;

import android.content.Intent;
import android.os.Bundle;

import androidx.fragment.app.Fragment;

import android.os.Handler;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.material.datepicker.MaterialDatePicker;
import com.google.android.material.datepicker.MaterialPickerOnPositiveButtonClickListener;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;


public class SearchFragment extends Fragment {


    public SearchFragment() {
        // Required empty public constructor
    }

    String[] persons = {"1 Person","2 Persons","3 Persons","4 Persons","5 Persons","6 Persons"};
    String noPerson;
    String from;
    String to;
    String date;
    ALoadingDialog aLoadingDialog;

    static final String[] LOCATIONS = {
            "Chintapalle",
            "Chintur",
            "Etapaka",
            "Kunavaram",
            "Vararamachandrapuram",
            "Ananthagiri",
            "Araku Valley",
            "Dumbriguda",
            "Ganagaraju Madugula",
            "Gudem Kotha Veedhi",
            "Hukumpeta",
            "Koyyuru",
            "Paderu",
            "Peda Bayalu",
            "Addateegala",
            "Devipatnam",
            "Gangavaram",
            "Maredumilli",
            "Munchingi Puttu",
            "Rajavommangi",
            "Rampachodavaram",
            "Y. Ramavaram",
            "Anakapalle",
            "Atchutapuram",
            "Butchayyapeta",
            "Chodavaram",
            "Devarapalli",
            "Elamanchili",
            "K.Kotapadu",
            "Kasimkota",
            "Munagapaka",
            "Paravada",
            "Rambilli",
            "Sabbavaram",
            "Cheedikada",
            "Golugonda",
            "Kotauratla",
            "Madugula",
            "Makavarapalem",
            "Nakkapalle",
            "Narsipatnam",
            "Nathavaram",
            "Payakaraopeta",
            "Ravikamatham",
            "Rolugunta",
            "Sarvasiddhi Rayavaram",
            "Anantapur Urban",
            "Anantapur Rural",
            "Atmakur",
            "Bukkaraya Samudram",
            "Garladinne",
            "Kudair",
            "Narpala",
            "Peddapappur",
            "Putlur",
            "Raptadu",
            "Singanamala",
            "Tadipatri",
            "Yellanur",
            "Gooty",
            "Guntakal",
            "Pamidi",
            "Peddavadugur",
            "Uravakonda",
            "Vajrakarur",
            "Vidapanakal",
            "Yadiki",
            "Beluguppa",
            "Bommanahal",
            "Brahmasamudram",
            "D.Hirehal",
            "Gummagatta",
            "Kalyandurg",
            "Kambadur",
            "Kanekal",
            "Kundurpi",
            "Rayadurg",
            "Settur",
            "Beerangi Kothakota",
            "Kalikiri",
            "Kurabalakota",
            "Madanapalle",
            "Mulakalacheruvu",
            "Nimmanapalle",
            "Pedda Thippasamudram",
            "Peddamandyam",
            "Ramasamudram",
            "Thamballapalle",
            "Valmikipuram",
            "Chitvel",
            "Railway Koduru",
            "Nandalur",
            "Obulavaripalle",
            "Penagalur",
            "Pullampeta",
            "Rajampet",
            "T Sundupalle",
            "Veeraballi",
            "Chinnamandyam",
            "Galiveedu",
            "Gurramkonda",
            "Kalakada",
            "Kambhamvaripalle",
            "Lakkireddypalle",
            "Pileru",
            "Ramapuram",
            "Rayachoti",
            "Sambepalli",
            "Bapatla",
            "Karlapalem",
            "Martur",
            "Parchur",
            "Pittalavanipalem",
            "Yeddanapudi",
            "Addanki",
            "Ballikurava",
            "Chinaganjam",
            "Chirala",
            "Inkollu",
            "Janakavarampanguluru",
            "Karamchedu",
            "Korisapadu",
            "Santhamaguluru",
            "Vetapalem",
            "Amruthalur",
            "Bhattiprolu",
            "Cherukupalle",
            "Kolluru",
            "Nagaram",
            "Nizampatnam",
            "Repalle",
            "Tsundur",
            "Vemuru",
            "Chittoor Rural",
            "Chittoor Urban",
            "Gangadhara Nellore",
            "Gudipala",
            "Irala",
            "Penumuru",
            "Pulicherla",
            "Puthalapattu",
            "Rompicherla",
            "Srirangarajapuram",
            "Thavanampalle",
            "Vedurukuppam",
            "Yadamarri",
            "Gudupalle",
            "Kuppam",
            "Ramakuppam",
            "Santhipuram",
            "Karvetinagar",
            "Nagari",
            "Nindra",
            "Palasamudram",
            "Vijayapuram",
            "Baireddipalle",
            "Bangarupalem",
            "Chowdepalle",
            "Gangavaram",
            "Palamaner",
            "Peddapanjani",
            "Punganur",
            "Sodam",
            "Somala",
            "Venkatagirikota",
            "Chagallu",
            "Devarapalle",
            "Gopalapuram",
            "Kovvur",
            "Nallajerla",
            "Nidadavole",
            "Peravali",
            "Tallapudi",
            "Undrajavaram",
            "Anaparthi",
            "Biccavolu",
            "Gokavaram",
            "Kadiam",
            "Korukonda",
            "Rajahmundry Urban",
            "Rajahmundry Rural",
            "Rajanagaram",
            "Rangampeta",
            "Seethanagaram",
            "Bhimadole",
            "Denduluru",
            "Eluru",
            "Kaikalur",
            "Kalidindi",
            "Mandavalli",
            "Mudinepalle",
            "Nidamarru",
            "Pedapadu",
            "Pedavegi",
            "Unguturu",
            "Buttayagudem",
            "Dwaraka Tirumala",
            "Jangareddygudem",
            "Jeelugu Milli",
            "Kamavarapukota",
            "Koyyalagudem",
            "Kukunoor",
            "Polavaram",
            "T. Narasapuram",
            "Velairpadu",
            "Agiripalle",
            "Chatrai",
            "Chintalapudi",
            "Lingapalem",
            "Musunuru",
            "Nuzvid",
            "Guntur East",
            "Guntur West",
            "Medikonduru",
            "Pedakakani",
            "Pedanandipadu",
            "Phirangipuram",
            "Prathipadu",
            "Tadikonda",
            "Thullur",
            "Vatticherukuru",
            "Chebrolu",
            "Duggirala",
            "Kakumanu",
            "Kollipara",
            "Mangalagiri",
            "Ponnur",
            "Tadepalle",
            "Tenali",
            "Gollaprolu",
            "Kajuluru",
            "Kakinada Rural",
            "Kakinada Urban",
            "Karapa",
            "U.Kothapalli",
            "Pedapudi",
            "Pithapuram",
            "Samalkota",
            "Thallarevu",
            "Gandepalli",
            "Jaggampeta",
            "Kirlampudi",
            "Kotananduru",
            "Peddapuram",
            "Prathipadu",
            "Rowthulapudi",
            "Sankhavaram",
            "Thondangi",
            "Tuni",
            "Yeleswaram",
            "Allavaram",
            "Amalapuram",
            "Island Polavaram",
            "Katrenikona",
            "Malikipuram",
            "Mamidikuduru",
            "Mummidivaram",
            "Razole",
            "Sakhinetipalle",
            "Uppalaguptam",
            "Ainavilli",
            "Alumuru",
            "Ambajipeta",
            "Atreyapuram",
            "Kothapeta",
            "Patha Gannavaram",
            "Ravulapalem",
            "Gangavaram",
            "Kapileswarapuram",
            "Mandapeta",
            "Ramachandrapuram",
            "Rayavaram",
            "Bapulapadu",
            "Gannavaram",
            "Gudivada",
            "Gudlavalleru",
            "Nandivada",
            "Pedaparupudi",
            "Unguturu",
            "Avanigadda",
            "Bantumilli",
            "Challapalli",
            "Ghantasala",
            "Guduru",
            "Koduru",
            "Kruthivennu",
            "Machilipatnam North",
            "Machilipatnam South",
            "Mopidevi",
            "Nagayalanka",
            "Pedana",
            "Kankipadu",
            "Movva",
            "Pamarru",
            "Pamidimukkala",
            "Penamaluru",
            "Thotlavalluru",
            "Vuyyuru",
            "Adoni",
            "Gonegandla",
            "Holagunda",
            "Kosigi",
            "Kowthalam",
            "Mantralayam",
            "Nandavaram",
            "Pedda Kadubur",
            "Yemmiganur",
            "C.Belagal",
            "Gudur",
            "Kallur",
            "Kodumur",
            "Kurnool Urban",
            "Kurnool Rural",
            "Orvakal",
            "Veldurthi",
            "Alur",
            "Aspari",
            "Chippagiri",
            "Devanakonda",
            "Halaharvi",
            "Krishnagiri",
            "Maddikera East",
            "Pattikonda",
            "Tuggali",
            "Atmakur",
            "Bandi Atmakur",
            "Jupadu Bungalow",
            "Kothapalle",
            "Midthuru",
            "Nandikotkur",
            "Pagidyala",
            "Pamulapadu",
            "Srisailam",
            "Velgodu",
            "Banaganapalle",
            "Bethamcherla",
            "Dhone",
            "Koilkuntla",
            "Owk",
            "Peapally",
            "Allagadda",
            "Chagalamarri",
            "Dornipadu",
            "Gadivemula",
            "Gospadu",
            "Kolimigundla",
            "Mahanandi",
            "Nandyal Rural",
            "Nandyal Urban",
            "Panyam",
            "Rudravaram",
            "Sanjamala",
            "Sirvella",
            "Uyyalawada",
            "Chandarlapadu",
            "Jaggayyapeta",
            "Kanchikacherla",
            "Nandigama",
            "Penuganchiprolu",
            "Vatsavai",
            "Veerullapadu",
            "A. Konduru",
            "Gampalagudem",
            "Reddigudem",
            "Tiruvuru",
            "Vissannapeta",
            "G.Konduru",
            "Ibrahimpatnam",
            "Mylavaram",
            "Vijayawada Rural",
            "Vijayawada North",
            "Vijayawada Central",
            "Vijayawada East",
            "Vijayawada West",
            "Dachepalle",
            "Durgi",
            "Gurazala",
            "Karempudi",
            "Macharla",
            "Machavaram",
            "Piduguralla",
            "Rentachintala",
            "Veldurthi",
            "Bollapalle",
            "Chilakaluripet",
            "Edlapadu",
            "Ipuru",
            "Nadendla",
            "Narasaraopet",
            "Nuzendla",
            "Rompicherla",
            "Savalyapuram",
            "Vinukonda",
            "Amaravathi",
            "Atchampet",
            "Bellamkonda",
            "Krosuru",
            "Muppalla",
            "Nekarikallu",
            "Pedakurapadu",
            "Rajupalem",
            "Sattenapalle",
            "Bhamini",
            "Gummalakshmipuram",
            "Jiyyammavalasa",
            "Kurupam",
            "Palakonda",
            "Seethampeta",
            "Veeraghattam",
            "Parvathipuram",
            "Balijipeta",
            "Garugubilli",
            "Komarada",
            "Makkuva",
            "Pachipenta",
            "Parvathipuram",
            "Salur",
            "Seethanagaram",
            "Chandra Sekhara Puram",
            "Darsi",
            "Donakonda",
            "Hanumanthuni Padu",
            "Kanigiri",
            "Konakanamitla",
            "Kurichedu",
            "Marripudi",
            "Pamuru",
            "Pedacherlo Palle",
            "Podili",
            "Ponnaluru",
            "Veligandla",
            "Ardhaveedu",
            "Bestawaripeta",
            "Cumbum",
            "Dornala",
            "Giddalur",
            "Komarolu",
            "Markapuram",
            "Peda Araveedu",
            "Pullalacheruvu",
            "Racherla",
            "Tarlupadu",
            "Tripuranthakam",
            "Yerragondapalem",
            "Chimakurthi",
            "Kondapi",
            "Kotha Patnam",
            "Maddipadu",
            "Mundlamuru",
            "Naguluppala Padu",
            "Ongole Rural",
            "Ongole Urban",
            "Santhanuthala Padu",
            "Singarayakonda",
            "Tangutur",
            "Thallur",
            "Zarugumilli",
            "Ananthasagaram",
            "Anumasamudrampeta",
            "Atmakuru",
            "Chejerla",
            "Kaluvoya",
            "Marripadu",
            "Sangam",
            "Sitarampuramu",
            "Udayagiri",
            "Gudluru",
            "Kandukur",
            "Kondapuram",
            "Lingasamudram",
            "Ulavapadu",
            "Varikuntapadu",
            "Voletivaripalem",
            "Allur",
            "Bogolu",
            "Dagadarthi",
            "Duttaluru",
            "Jaladanki",
            "Kaligiri",
            "Kavali",
            "Kodavaluru",
            "Vidavaluru",
            "Vinjamuru",
            "Buchireddypalem",
            "Indukurpet",
            "Kovuru",
            "Manubolu",
            "Muttukuru",
            "Nellore Urban",
            "Nellore Rural",
            "Podalakuru",
            "Rapuru",
            "Saidapuramu",
            "Thotapalligudur",
            "Venkatachalam",
            "Bathalapalle",
            "Chennekothapalle",
            "Dharmavaram",
            "Kanaganapalle",
            "Mudigubba",
            "Ramagiri",
            "Tadimarri",
            "Amadagur",
            "Gandlapenta",
            "Kadiri",
            "Lepakshi",
            "Nallacheruvu",
            "Nambulipulikunta",
            "Tanakal",
            "Agali",
            "Amarapuram",
            "Chilamathur",
            "Gudibanda",
            "Hindupur",
            "Madakasira",
            "Parigi",
            "Penukonda",
            "Roddam",
            "Rolla",
            "Somandepalle",
            "Talupula",
            "Bukkapatnam",
            "Gorantla",
            "Kothacheruvu",
            "Nallamada",
            "Obuladevaracheruvu",
            "Puttaparthi",
            "Ichchapuram",
            "Kanchili",
            "Kaviti",
            "Mandasa",
            "Nandigam",
            "Palasa",
            "Sompeta",
            "Vajrapukothuru",
            "Amadalavalasa",
            "Burja",
            "Etcherla",
            "Ganguvarisigadam",
            "Gara",
            "Jalumuru",
            "Laveru",
            "Narasannapeta",
            "Polaki",
            "Ponduru",
            "Ranastalam",
            "Sarubujjili",
            "Srikakulam",
            "Hiramandalam",
            "Kotabommali",
            "Kothuru",
            "Lakshminarsupeta",
            "Meliaputti",
            "Pathapatnam",
            "Santhabommali",
            "Saravakota",
            "Tekkali",
            "Balayapalli",
            "Chilakuru",
            "Chittamuru",
            "Dakkili",
            "Gudur",
            "Kota",
            "Vakadu",
            "Venkatagiri",
            "K. V. B. Puram",
            "Nagalapuram",
            "Narayanavanam",
            "Pichatur",
            "Renigunta",
            "Srikalahasti",
            "Thottambedu",
            "Yerpedu",
            "Buchinaidu Kandriga",
            "Doravarisatramu",
            "Naidupeta",
            "Ojili",
            "Pellakuru",
            "Satyavedu",
            "Sullurpeta",
            "Tada",
            "Varadaiahpalem",
            "Chandragiri",
            "Chinnagottigallu",
            "Pakala",
            "Puttur",
            "Ramachandrapuram",
            "Tirupati Rural",
            "Tirupati Urban",
            "Vadamalapeta",
            "Yerravaripalem",
            "Anandapuram",
            "Bheemunipatnam",
            "Padmanabham",
            "Seethammadhara",
            "Visakhapatnam Rural",
            "Gajuwaka",
            "Gopalapatnam",
            "Maharanipeta",
            "Mulagada",
            "Pedagantyada",
            "Pendurthi",
            "Badangi",
            "Bobbili",
            "Dattirajeru",
            "Gajapathinagaram",
            "Mentada",
            "Ramabhadrapuram",
            "Therlam",
            "Cheepurupalle",
            "Garividi",
            "Gurla",
            "Merakamudidam",
            "Rajam",
            "Regidi Amadalavalasa",
            "Santhakaviti",
            "Vangara",
            "Bhogapuram",
            "Bondapalle",
            "Denkada",
            "Gantyada",
            "Jami",
            "Kothavalasa",
            "Lakkavarapukota",
            "Nellimarla",
            "Pusapatirega",
            "Srungavarapukota",
            "Vepada",
            "Vizianagaram Rural",
            "Vizianagaram Urban",
            "Akividu",
            "Bhimavaram",
            "Kalla",
            "Palacoderu",
            "Undi",
            "Veeravasaram",
            "Achanta",
            "Mogalthur",
            "Palakollu",
            "Penugonda",
            "Penumantra",
            "Poduru",
            "T.Narasapuram",
            "Yelamanchili",
            "Attili",
            "Ganapavaram",
            "Iragavaram",
            "Pentapadu",
            "Tadepalligudem",
            "Tanuku",
            "Atlur",
            "B.Kodur",
            "Badvel",
            "Brahmamgarimattam",
            "Chapad",
            "Duvvur",
            "Gopavaram",
            "Kalasapadu",
            "Khajipet",
            "Porumamilla",
            "S.Mydukur",
            "Sri Avadhutha Kasinayana",
            "Jammalamadugu",
            "Kondapuram",
            "Muddanur",
            "Mylavaram",
            "Peddamudium",
            "Proddatur",
            "Rajupalem",
            "Chennur",
            "Chinthakommadinne",
            "Kadapa",
            "Kamalapuram",
            "Pendlimarri",
            "Sidhout",
            "Vallur",
            "Vontimitta",
            "Yerraguntla",
            "Chakrayapet",
            "Lingala",
            "Pulivendla",
            "Simhadripuram",
            "Thondur",
            "Veerapunayunipalle",
            "Vempalle"
    };



    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_search, container, false);
        AutoCompleteTextView personss = view.findViewById(R.id.searchPersons);
        AutoCompleteTextView searchFrom = view.findViewById(R.id.searchFrom);
        AutoCompleteTextView searchTo = view.findViewById(R.id.searchTo);
        TextView date = view.findViewById(R.id.timePersonDate);
        Button searchButton = view.findViewById(R.id.SearchButton);
        aLoadingDialog = new ALoadingDialog(getContext());
        ArrayAdapter<String> adapter = new ArrayAdapter<>(
                requireContext(), android.R.layout.simple_dropdown_item_1line, LOCATIONS
        );
        ArrayAdapter<String> adapterperson = new ArrayAdapter<>(
                requireContext(), android.R.layout.simple_dropdown_item_1line, persons
        );

        personss.setAdapter(adapterperson);



        personss.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {

                if(i==0){
                    noPerson = "1";
//                    Toast.makeText(getActivity(), "Person 1", Toast.LENGTH_SHORT).show();
                }
                else if(i==1){
                    noPerson = "2";
//                    Toast.makeText(getActivity(), "Person 2", Toast.LENGTH_SHORT).show();
                }
                else if(i==2){
                    noPerson = "3";
//                    Toast.makeText(getActivity(), "Person 3", Toast.LENGTH_SHORT).show();
                }
                else if(i==3){
                    noPerson = "4";
//                    Toast.makeText(getActivity(), "Person 4", Toast.LENGTH_SHORT).show();
                }
                else if(i==4){
                    noPerson = "5";
//                    Toast.makeText(getActivity(), "Person 5", Toast.LENGTH_SHORT).show();
                }
                else if(i==5){
                    noPerson = "6";
//                    Toast.makeText(getActivity(), "Person 6", Toast.LENGTH_SHORT).show();
                }

            }
        });

        date.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                MaterialDatePicker<Long> materialDatePicker = MaterialDatePicker.Builder.datePicker()
                        .setTitleText("Select Travelling Date")
                        .setSelection(MaterialDatePicker.todayInUtcMilliseconds())
                        .build();
                materialDatePicker.addOnPositiveButtonClickListener(new MaterialPickerOnPositiveButtonClickListener<Long>() {
                    @Override
                    public void onPositiveButtonClick(Long selection) {
                        String tdate = new SimpleDateFormat("dd-MM-yyy", Locale.getDefault()).format(new Date(selection));
                        date.setText(tdate);
                    }
                });
                materialDatePicker.show(getActivity().getSupportFragmentManager(), "tag");
            }
        });

        searchFrom.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                from = (String) adapterView.getItemAtPosition(i);
            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });



        searchTo.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                to = (String) adapterView.getItemAtPosition(i);
            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });

        searchButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String from = searchFrom.getText().toString();
                String to = searchTo.getText().toString();

                Intent i = new Intent(getActivity(), SearchResultsActivity.class);
                i.putExtra("from", from);
                i.putExtra("to",to);
                startActivity(i);
            }
        });

        searchFrom.setAdapter(adapter);
        searchTo.setAdapter(adapter);
        return view;
    }
}